name: Blog in Readme

on:
  workflow_dispatch:
  schedule:
    # Once a week
    - cron: 0 7 * * 1

jobs:
  updateposts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://adam.kostarelas.com/index.xml
          committer_username: GitHub Actions[Bot]